### ISSUE TITLE
Написание документации по модели MVC 

### ISSUE THREAD

**Issue by sa1rac** [fate-studio/goodwin#2]
Документация должна затрагивать каждый элемент этой модели  и содержать примеры как сайтов, так и реализации. В будущем нужно будет дополнить пример шаблоном реализации модели на движке Goodwin

**Comment by sa1rac** [comment]
Взял 

1. 

- [ ] 

-

**Comment by Kabaletskih** [comment]
> Взял

Google Docs:
Login: dmitriy.kabaletskih@gmail.com
Pass: FacelessLegion312
File: Goodwin manual

**Comment by sa1rac** [comment]
> > Взял
> 
> Google Docs:
> Login: [dmitriy.kabaletskih@gmail.com](mailto:dmitriy.kabaletskih@gmail.com)
> Pass: FacelessLegion312
> File: Goodwin manual

В него писать?
